# Generated by Django 4.1.2 on 2022-10-10 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100, verbose_name='Номер заказа')),
                ('status', models.CharField(choices=[('New', 'New'), ('In Process', 'In Process'), ('Stored', 'Stored'), ('Send', 'Send')], default='New', max_length=20, verbose_name='Статуc')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
